quarkus.http.port=8082

# choose sink: sftp | local
sink.mode=local

# local sink settings (used only when sink.mode=local)
local.outputDir=/data/pos/import

mqtt.broker=tcp://20.126.206.192:1883
mqtt.client=schapfl-sync-client
mqtt.username=testclient
mqtt.password=&UWa=gBEtJ9&iLg9M-6=L\$
mqtt.qos=1
mqtt.topic=schapfl/articlesync

schapfl.store-number=1
schapfl.lane-number=1

# SFTP destination
sftp.host=<host-name>
sftp.port=22
sftp.username=<username>

# choose ONE of the following auth modes:
sftp.password=<secret>

# host keys
sftp.knownHosts=   # can be empty to disable strict checking
sftp.strictHostKeyChecking=no             # yes/no

sftp.privateKey=
sftp.privateKeyPassphrase=

# remote folder
sftp.remoteDir=/test

# retry (optional)
sftp.retry.maxAttempts=5
sftp.retry.delayMillis=1000
